# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Nginx port
      - "5173:5173"  # Vite HMR port (default port for Vite dev server)
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "8000:9000"
    volumes:
      - ./server:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=glossvault
      - DB_USERNAME=ell595
      - DB_PASSWORD=digdug
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=glossvault
      - MYSQL_USER=ell595
      - MYSQL_PASSWORD=digdug
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client/public/build:/usr/share/nginx/html/
      - ./server:/var/www/html:delegated
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email e.fraser3@gmail.com --agree-tos --no-eff-email --staging -d glossvault.ell595.site -d api-glosvault.ell595.site --dry-run

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  certbot-etc:
  certbot-var: